version: '3.8'

services:
  laravel:
    build: .
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passer123
      MYSQL_DATABASE: pharma
      MYSQL_USER: root
      MYSQL_PASSWORD: passer123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
